### ISSUE TITLE
Create a Contact Page of this Website

### ISSUE THREAD

**Issue by Geeks-Arpan** [rko0211/jgec-previous-year-question-paper#1]

**Comment by Sneha123-zudo** [comment]
I'm intrested in fixing this issue , please assign me this issue

**Comment by rko0211** [comment]
@Geeks-Arpan you have 2 days to solve this issue. And kindly read the README. Md file and Open PR in test branch only.

**Comment by rko0211** [comment]
Hey @Geeks-Arpan what is the update about this issue.

**Comment by rko0211** [comment]
@Geeks-Arpan  today is the last date after that this issue will be assigned to other contributor. Kindly reply on this if you face any issue during this .

**Comment by Sapta-Dev27** [comment]
If he is not working, kindly assign the task to me then after today ...I
would love to contribute in the project

**Comment by rko0211** [comment]
OK as @Geeks-Arpan  is not responding so i have decided to assign this issue to other.

**Comment by rko0211** [comment]
@Sapta-Dev27  go ahead you have 3 days to complete this task.

**Comment by Sapta-Dev27** [comment]
Issue #1 was assigned to me yesterday
I have solved it
PR is made
Kindly check it

**Comment by Sapta-Dev27** [comment]
[Screen recording 2024-01-08 15.46.37.webm](https://github.com/rko0211/jgec-previous-year-question-paper/assets/149397021/c66467c3-5138-441b-8700-dd3236f5c988)
This is the demo of the contact page I made

**Comment by rko0211** [comment]
Hey i need to check responsiveness of this page. So give me website link

**Comment by Sapta-Dev27** [comment]
Thanks, I'll check it out.
I know how to host it through github pages and vercel..
I will host the website and share the link with you
