### ISSUE TITLE
Create a Proper Redirectable Navlink For Email In Footer Bar

### ISSUE THREAD

**Issue by swarnade** [rko0211/jgec-previous-year-question-paper#11]
![image](https://github.com/rko0211/jgec-previous-year-question-paper/assets/78968218/a322f5ed-b68a-4a9a-81e8-e4c77b157c53)
This Does Not Redirect

**Comment by rko0211** [comment]
Go ahead @swarnade

**Comment by rko0211** [comment]
What is the update @swarnade

**Comment by swarnade** [comment]
Sorry , My laptop Was In Issue For A While

**Comment by rko0211** [comment]
Ok
