### ISSUE TITLE
the hover effect on the cards need to be fixed

### ISSUE THREAD

**Issue by deepbeatz** [rko0211/jgec-previous-year-question-paper#18]
when we hover on the cards the changed color is nit good looking and also when the mouse goes out of the card the color quickly vanishes whereas it should vanish with an ease just like it came with an ease when card is hovered...

@rko0211 assign me this issue under apertre24

**Comment by pseudofool** [comment]
i would like to work on this issue, please assign it to me.

**Comment by rko0211** [comment]
Go ahead @deepbeatz and read the README. md file. And Open your PR in Test branch only.

**Comment by deepbeatz** [comment]
![Uploading Screenshot 2024-01-05 124326.png…]()

**Comment by deepbeatz** [comment]
what should i do about this?

**Comment by deepbeatz** [comment]
![Uploading Screenshot 2024-01-05 144923.png…]()

**Comment by deepbeatz** [comment]
im facing this problem
plz let me know what to do

**Comment by deepbeatz** [comment]
<img width="960" alt="Screenshot 2024-01-05 144923" src="https://github.com/rko0211/jgec-previous-year-question-paper/assets/79015311/351b63a1-7056-45c0-ba34-4253e62e8909">

**Comment by rko0211** [comment]
Do you have done any changes in the repository. If yes then select Test branch in my repository side then create a PR.

**Comment by deepbeatz** [comment]
no worries i have succesfully made a pull request with the title "added the css changes" #23

**Comment by deepbeatz** [comment]
plz check and merge and then close issue @rko0211
