### ISSUE TITLE
Create a beautiful README file for the repository

### ISSUE THREAD

**Issue by rko0211** [rko0211/jgec-previous-year-question-paper#2]

**Comment by AnitSarkar123** [comment]
Assign me this issue under Aperture '24

**Comment by rko0211** [comment]
Sure on 3rd Jan 2024 i will assign this issue to you.Thank you for your interest.

**Comment by komal-agarwal5** [comment]
I would like to work on this issue . Please assign it to me.

**Comment by rko0211** [comment]
@komal-agarwal5  go ahead
