### ISSUE TITLE
Create a Responsive and beautiful About page

### ISSUE THREAD

**Issue by rko0211** [rko0211/jgec-previous-year-question-paper#4]
Create a beautiful About page and linked it with the navbar . Text content can be of any poem and image must be of Pokemon realated.

**Comment by AnitSarkar123** [comment]
I want to contribute on it but what I am going to write on it?. Can you please said to me that. Because I am not from JGEC.

**Comment by rko0211** [comment]
> I want to contribute on it but what I am going to write on it?. Can you please said to me that. Because I am not from JGEC. Assign me under Aperture'24

Design by you own but Page content can be any story/poem text and if you want to add image in this page then must add Pokemon images only.

**Comment by AnitSarkar123** [comment]
can i use ui library or only HTML,CSS

**Comment by rko0211** [comment]
Whatever you want ....

**Comment by rko0211** [comment]
Go ahead @AnitSarkar123

**Comment by rko0211** [comment]
Whats the update

**Comment by Sneha123-zudo** [comment]
I am intrested in this issue

**Comment by AnitSarkar123** [comment]
> Whats the update 
> 

@rko0211 assigned it to anyother because of some reason I don't able to contribute

**Comment by rko0211** [comment]
> > Whats the update
> 
> @rko0211 assigned it to anyother because of some reason I don't able to contribute

Actually you have to inform me other wise how i can come to know it

**Comment by rko0211** [comment]
OK Go ahead @Sneha123-zudo
