### ISSUE TITLE
Feature_Request in README.md

### ISSUE THREAD

**Issue by apu52** [rko0211/jgec-previous-year-question-paper#49]
**Describe the feature you are requesting**

Hello Sir,
I want to add some cool badges in this repo like
- open issues
- contributor
- open PR
- last commites
this type of cool API badges
It will be very helpful to showcase the stats of your Repo as well as will attract more contributors.
**Additional context(if any)**

![image](https://github.com/rko0211/jgec-previous-year-question-paper/assets/114172928/9fce6a25-4320-4042-af88-470c1e0a87e4)

***Are you contributing under any open-source program ?***

APERTRE'24

**Comment by apu52** [comment]
@rko0211 Please assign me this issue under APERTRE'24

**Comment by rko0211** [comment]
OK go @apu52
