### ISSUE TITLE
Create Responsive and beautiful Purpose page

### ISSUE THREAD

**Issue by rko0211** [rko0211/jgec-previous-year-question-paper#5]
Create a beautiful Purpose page and linked it with the navbar . Text content can be of any poem and image must be of Pokemon realated.

**Comment by Sneha123-zudo** [comment]
I'm intrested in fixing this issue , please assign me this issue

**Comment by rko0211** [comment]
Ok @Sneha123-zudo  go ahead you have 2 days to complete this task. Thanks for your interest in our project.
