### ISSUE TITLE
adding scroll animations and get in touch button 

### ISSUE THREAD

**Issue by 123shreyanvi** [rko0211/jgec-previous-year-question-paper#52]
on scrolling there will be animations on scroll like eg zoom flip fade etc..It will make it more attractive to the user
get in touch button will open a form that saves data on google sheets

**Comment by 123shreyanvi** [comment]
plz do assign me this

**Comment by rko0211** [comment]
Obviously, based on your changes I will add the labels in your PR, no worries

**Comment by 123shreyanvi** [comment]
Okay

**Comment by rko0211** [comment]
How work is going on @123shreyanvi

**Comment by rko0211** [comment]
What is the update

**Comment by 123shreyanvi** [comment]
> What is the update

I have made the pr
