### ISSUE TITLE
Feature change

### ISSUE THREAD

**Issue by arghadipmanna101** [rko0211/jgec-previous-year-question-paper#59]
- Will do Dark mode style change .

**Comment by arghadipmanna101** [comment]
please assign me in this work

**Comment by arghadipmanna101** [comment]
I want to modify the dark and light button and make it engaging.

![image](https://github.com/rko0211/jgec-previous-year-question-paper/assets/130065095/9db3aae0-a1de-4f42-b609-f37c9c47bd8e)

**Comment by arghadipmanna101** [comment]
can i do this work?

**Comment by rko0211** [comment]
Ok go ahead @arghadipmanna101

**Comment by arghadipmanna101** [comment]
thank you
