### ISSUE TITLE
Add Light/Dark Mode in the Home page

### ISSUE THREAD

**Issue by rko0211** [rko0211/jgec-previous-year-question-paper#6]

**Comment by Suman599** [comment]
Pls assign me this issue

**Comment by rko0211** [comment]
What is the update @Suman599

**Comment by Suman599** [comment]
> What is the update @Suman599

I have tried but can't do anything about the about and purpose page in the mobile device. Light mode button is getting clicked if I select about or purpose in mobile.

**Comment by rko0211** [comment]
![Screen Shot 2024-01-07 at 11 04 39](https://github.com/rko0211/jgec-previous-year-question-paper/assets/97402824/84c40cd8-2445-4e2a-b832-4ba2765f7854)

Kindly check in mobile device if you are going to click about option from navbar then it can't be clicked . You may solve it by working on navbar Z-index property

**Comment by rko0211** [comment]
Kindly work on updated branch and make the button beautiful . Take reference from internet

**Comment by Suman599** [comment]
Pls review the website then I will send the PR once approved - https://suman599.github.io/light-and-dark-mode/

**Comment by rko0211** [comment]
Nice but there is another issue that is in Mobile Desktop mode the website is not responsive. Kindly check it

**Comment by Suman599** [comment]
> Nice but there is another issue that is in Mobile Desktop mode the website is not responsive and mobile view is also not responsive . Kindly check it

Pls check the website so that I can send the pull request- https://suman599.github.io/light-and-dark-mode/

**Comment by rko0211** [comment]
bro still there is issue listen work  on updated branch and just add a button in the home page(index.html)
Then create a js file to handle the behavior color of the card, background color etc. don;t touch in the structure of the page .
and you can check it by your phone also... So try it again ...keep it up

**Comment by Suman599** [comment]
> bro still there is issue listen work on updated branch and just add a button in the home page(index.html) Then create a js file to handle the behavior color of the card, background color etc. don;t touch in the structure of the page . and you can check it by your phone also... So try it again ...keep it up

I have done all of that. The structure of the page is intact as it was provided and I just changed the color of the card to light green. The background color is intact. I have also added the button.  Now I cannot exactly get what u are telling to change.I have done all things u mentioned above.

**Comment by rko0211** [comment]
But your changes affect the responsiveness of the website.

**Comment by Suman599** [comment]
> But your changes affect the responsiveness of the website.

I just checked the website is fully responsive. All buttons are working perfectly. Can u pls send me a screenshot where the website is not responding.

**Comment by rko0211** [comment]
![Screen Shot 2024-01-07 at 23 30 28](https://github.com/rko0211/jgec-previous-year-question-paper/assets/97402824/2ae67dca-872e-46d9-9ad0-6c78dc6f3fc9)
![Screen Shot 2024-01-07 at 23 29 59](https://github.com/rko0211/jgec-previous-year-question-paper/assets/97402824/e09122a9-6414-4d49-8c17-8e76ecec3121)
Bro Horizontal scroll bar is there kindly observe it . or you can run application in your mobile device also 
you will understand

**Comment by Suman599** [comment]
Ok I will remove the horizontal scroll bar.Except that is there any problem?

**Comment by rko0211** [comment]
No need to add the text for dark and light mode . And make the website responsive.

**Comment by rko0211** [comment]
Hey @Suman599  kindly send PR one more time in **Updated main** branch its my humble request to you.

**Comment by Suman599** [comment]
> Hey @Suman599 kindly send PR one more time in **Updated main** branch its my humble request to you.

Ok I will send PR by evening
