### ISSUE TITLE
Search Engine Optimisation

### ISSUE THREAD

**Issue by arghadipmanna101** [rko0211/jgec-previous-year-question-paper#61]
- Search Engine Optimisation and performance enhancement.

![Screenshot 2024-01-19 031008](https://github.com/rko0211/jgec-previous-year-question-paper/assets/130065095/c0d24efd-cca3-46f3-9b3a-103bab2a55ff)

**Comment by arghadipmanna101** [comment]
- Well Convert .jpg and .png to webp
- Well add meta tags
To enhancement performance of Search Engine.

**Comment by rko0211** [comment]
No need

**Comment by arghadipmanna101** [comment]
ok
