### ISSUE TITLE
Change Navbar Design

### ISSUE THREAD

**Issue by rko0211** [rko0211/jgec-previous-year-question-paper#7]

**Comment by Sneha123-zudo** [comment]
I'm intrested in fixing this issue please me this issue

**Comment by rko0211** [comment]
> I'm intrested in fixing this issue please me this issue

Sure go ahead @Sneha123-zudo and thank you for your interest to contribute in my project. Before any contribution kindly read the **README.md** and **CONTRIBUTING.md** file carefully.
