### ISSUE TITLE
Fix the links in the navbar such as home , about  , purpose and contact

### ISSUE THREAD

**Issue by Sapta-Dev27** [rko0211/jgec-previous-year-question-paper#8]
I would like the fix the bug in the navbar in the links sections . As of now on clicking on the home , about , purpose and contact section , the page is redirected to a empty GitHub page . I would like to fix this issue such that on clicking on the about, it is taken to the about section of the website . Similarly on clicking on purpose it is redirected to the purpose section of the website and so on

**Comment by rko0211** [comment]
Please see the issue section carefully there you will get every issue individually. so kindly comment there i will assign you. Thank you for your interest in opensource.
